"""Seed the TAP Response Knowledge doctype with direct-response examples."""

from __future__ import annotations

from typing import Any, Dict, List

import frappe


DOCTYPE = "TAP Response Knowledge"
CACHE_KEY = "tap_ai:direct_response_knowledge:v1"


def _ensure_doctype_loaded() -> None:
    if frappe.db.exists("DocType", DOCTYPE):
        return

    frappe.reload_doc("tap_ai", "doctype", "tap_response_knowledge")


SEED_DATA: List[Dict[str, Any]] = [
    {
        "title": "Greetings - Hi",
        "category": "Greetings",
        "subcategory": "General Greetings",
        "student_query": "Hi",
        "alternate_queries": "Hii",
        "response": "Hi there! 👋 Great to hear from you! I'm here to help you learn and grow. Shall we get started?",
        "match_type": "Fuzzy",
        "priority": 100,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Hello",
        "category": "Greetings",
        "subcategory": "General Greetings",
        "student_query": "Hello",
        "alternate_queries": "Helo\n👋",
        "response": "Hello! 😊 I'm TAP Buddy, your learning companion! Ready to do something amazing today?",
        "match_type": "Fuzzy",
        "priority": 99,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Greetings - Hey",
        "category": "Greetings",
        "subcategory": "General Greetings",
        "student_query": "Hey",
        "alternate_queries": "sup",
        "response": "Hey! 🌟 So happy you're here! Let's make today's learning count. Your activity is waiting!",
        "match_type": "Fuzzy",
        "priority": 98,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Greetings - Bye",
        "category": "Greetings",
        "subcategory": "Goodbye / signing off",
        "student_query": "Bye",
        "alternate_queries": "Tata",
        "response": "Bye! 👋 You did great today! Come back soon — there's lots more fun learning ahead! 🌟",
        "match_type": "Fuzzy",
        "priority": 95,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Goodbye",
        "category": "Greetings",
        "subcategory": "Goodbye / signing off",
        "student_query": "Goodbye",
        "alternate_queries": "baad mein",
        "response": "See you soon! 😊 Don't forget to complete your activity before you go — it only takes a few minutes!",
        "match_type": "Fuzzy",
        "priority": 94,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Good Morning",
        "category": "Greetings",
        "subcategory": "Good morning / time greetings",
        "student_query": "good morning",
        "alternate_queries": "Good morning",
        "response": "Good morning! ☀️ Hope your day is off to a great start!",
        "match_type": "Fuzzy",
        "priority": 93,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Gm",
        "category": "Greetings",
        "subcategory": "Good morning / time greetings",
        "student_query": "Gm",
        "alternate_queries": "gm",
        "response": "Good morning! 🌅 A new day, a new chance to learn! Let's make it count together. 💪",
        "match_type": "Fuzzy",
        "priority": 92,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Encouraging",
    },
    {
        "title": "Greetings - Shubh Prabhat",
        "category": "Greetings",
        "subcategory": "Good morning / time greetings",
        "student_query": "shubh prabhat",
        "alternate_queries": "Shubh Prabhat",
        "response": "Good morning! ☀️ Hope your day is off to a great start! Ready to learn something new today?",
        "match_type": "Fuzzy",
        "priority": 91,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Festival Wishes",
        "category": "Greetings",
        "subcategory": "Festival / occasion wishes",
        "student_query": "happy diwali",
        "alternate_queries": "eid mubarak\nhappy holi\nmerry christmas",
        "response": "Happy celebrations to you and your family! 🎉✨ Hope this special day brings lots of joy! When you're ready, I'm here for your learning activity.",
        "match_type": "Fuzzy",
        "priority": 90,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Celebratory",
    },
    {
        "title": "Greetings - Happy Festivities",
        "category": "Greetings",
        "subcategory": "Festival / occasion wishes",
        "student_query": "happy festivities",
        "alternate_queries": "Happy festivities",
        "response": "Wishing you a wonderful celebration! 🎊 Enjoy the festivities — and come back to your activity when you are ready 😊",
        "match_type": "Fuzzy",
        "priority": 89,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Celebratory",
    },
    {
        "title": "Greetings - Happy Summer Holiday",
        "category": "Greetings",
        "subcategory": "Festival / occasion wishes",
        "student_query": "happy summer holiday",
        "alternate_queries": "Happy summer holiday",
        "response": "Enjoy your holidays and come back to your activity when you are ready 😊",
        "match_type": "Fuzzy",
        "priority": 88,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Good Night",
        "category": "Greetings",
        "subcategory": "Good Night Messages",
        "student_query": "Good night",
        "alternate_queries": "good night",
        "response": "Aww, good night! 😊 Sleep tight! And if you haven't finished today's activity yet, it'll be right here waiting for you tomorrow. You've got this! 💪",
        "match_type": "Fuzzy",
        "priority": 87,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Greetings - Sleep Well",
        "category": "Greetings",
        "subcategory": "Good Night Messages",
        "student_query": "sone jaa rahi hu",
        "alternate_queries": "sone jaa raha hu",
        "response": "Good night! 🌙 Rest well. A fresh mind learns best! 💪 See you tomorrow for your TAP activity. Sweet dreams!",
        "match_type": "Fuzzy",
        "priority": 86,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Gibberish - Mixed Up Text",
        "category": "Gibberish",
        "subcategory": "Random character spam",
        "student_query": "No vowels",
        "alternate_queries": ">4 same letters",
        "response": "Oops! 😄 Looks like something got mixed up. No worries",
        "match_type": "Fuzzy",
        "priority": 85,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Playful",
    },
    {
        "title": "Gibberish - Repeated Chars",
        "category": "Gibberish",
        "subcategory": "Random character spam",
        "student_query": "repeated chars",
        "alternate_queries": "",
        "response": "Hmm, I didn't quite catch that! 🤔 Maybe your phone slipped?",
        "match_type": "Fuzzy",
        "priority": 84,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Playful",
    },
    {
        "title": "Gibberish - No Dictionary Match",
        "category": "Gibberish",
        "subcategory": "Random character spam",
        "student_query": "no dictionary match",
        "alternate_queries": "",
        "response": "I think something got jumbled there! 😊 No problem at all.",
        "match_type": "Fuzzy",
        "priority": 83,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Playful",
    },
    {
        "title": "Gibberish - Emoji Spam",
        "category": "Gibberish",
        "subcategory": "Emoji spam / reactions",
        "student_query": "5+ emojis",
        "alternate_queries": "emoji-only message",
        "response": "Love the energy! 🔥 When you're ready, do the activity and let's keep the learning going! 💪",
        "match_type": "Fuzzy",
        "priority": 82,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Playful",
    },
    {
        "title": "Gibberish - Repeated Emoji",
        "category": "Gibberish",
        "subcategory": "Emoji spam / reactions",
        "student_query": "repeated emoji",
        "alternate_queries": "",
        "response": "So much excitement! ✨ I love it! Ready to do your submission?",
        "match_type": "Fuzzy",
        "priority": 81,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Playful",
    },
    {
        "title": "Short Reply - Ok",
        "category": "Gibberish",
        "subcategory": "Very short / unclear messages mid-flow",
        "student_query": "Ok",
        "alternate_queries": "K\nHmm",
        "response": "Got it! 😊",
        "match_type": "Fuzzy",
        "priority": 80,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Short Reply - Acha",
        "category": "Gibberish",
        "subcategory": "Very short / unclear messages mid-flow",
        "student_query": "Acha",
        "alternate_queries": "thik hai",
        "response": "Sounds good! 👍",
        "match_type": "Fuzzy",
        "priority": 79,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Identity - Who Are You",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "who are you",
        "alternate_queries": "your name\nmam aapka naam",
        "response": "I'm TAP Buddy! ✨ Your friendly learning companion from TAP (The Apprentice Project). I'm here to help you learn 21st century skills like leadership and creative thinking — through fun videos and activities! Ready to get started?",
        "match_type": "Fuzzy",
        "priority": 78,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Identity - Aap Kaun Ho",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "aap kaun ho",
        "alternate_queries": "tap buddy kaun hai",
        "response": "Hi! I'm TAP Buddy 😊 your learning didi! I’ve been sent by your teacher to help you. I share videos, ask questions, and help you grow. Think of me as your digital study partner! What would you like to do today?",
        "match_type": "Fuzzy",
        "priority": 77,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - What Is TAP Program",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What is TAP Program",
        "alternate_queries": "What is TAP program",
        "response": "The TAP Program is a super fun program just for you! It is organized by your school, so you definitely don't want to miss it! 🏫✨",
        "match_type": "Fuzzy",
        "priority": 76,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - What Is Summer Camp",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What is Summer Camp?",
        "alternate_queries": "What is Summer Camp",
        "response": "Summer Camp is an exciting 4-week event. You can earn points just by completing and sending in your activities! ☀️🏆",
        "match_type": "Fuzzy",
        "priority": 75,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - What Are Videos",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What are videos?",
        "alternate_queries": "What are activity videos?",
        "response": "Activity Videos are short, interesting videos (2-4 minutes long). They cover topics you are already learning about in school. 📽️🧠",
        "match_type": "Fuzzy",
        "priority": 74,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - What Are Activity Videos About",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What are activity video about?",
        "alternate_queries": "What are activity videos about?",
        "response": "These videos help you learn great skills, like speaking confidently, original thinking, and expressing your ideas. They are super helpful for school and for life! 🗣️💡",
        "match_type": "Fuzzy",
        "priority": 73,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - When Will I Get Video",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "When will I get video?",
        "alternate_queries": "When will I get videos?",
        "response": "You will get new activity videos every Tuesday evening.",
        "match_type": "Fuzzy",
        "priority": 72,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - What Is Activity",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What is activity?",
        "alternate_queries": "What is an activity?",
        "response": "An activity is a simple, easy submission for you to do after you watch the video. It only takes about 10–20 minutes to finish! ✅📝",
        "match_type": "Fuzzy",
        "priority": 71,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - What Are Points",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What are points",
        "alternate_queries": "What are the points?",
        "response": "Points are your reward for all your hard work! You earn them by watching the videos and sending in your activities. 🌟💰",
        "match_type": "Fuzzy",
        "priority": 70,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - Special Gem",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "what is a special gem",
        "alternate_queries": "special gem",
        "response": "Special gems are cool, exclusive rewards! You can show them off to your friends to show how great you are doing. 💎😎",
        "match_type": "Fuzzy",
        "priority": 69,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - Quiz Points",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "How many points for the quiz?",
        "alternate_queries": "quiz points",
        "response": "You can earn 5 points for completing the quiz.",
        "match_type": "Fuzzy",
        "priority": 68,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - Streak Reset",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "Why will streaks start from zero",
        "alternate_queries": "streak reset",
        "response": "If you get very busy and miss a week, your streak will reset to zero. But don't worry, you can start a new streak again right away!",
        "match_type": "Fuzzy",
        "priority": 67,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Program - Surprises",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "what are the surprises?",
        "alternate_queries": "surprises",
        "response": "I feel proud of rockstars like you! Thus, to celebrate your effort, I bring special surprises. Keep doing your activities to win them!",
        "match_type": "Fuzzy",
        "priority": 66,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Friendly",
    },
    {
        "title": "Program - First Activity Soon",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "When will I get my first activity?",
        "alternate_queries": "first activity",
        "response": "I will share your first activity with you very soon!",
        "match_type": "Fuzzy",
        "priority": 65,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Program - First Activity Content",
        "category": "Trying to Talk",
        "subcategory": "Who are you / what is TAP Buddy?",
        "student_query": "What will be my first activity?",
        "alternate_queries": "first activity content",
        "response": "It will be something very interesting! I am talking to your teacher right now to pick the best activity for you.",
        "match_type": "Fuzzy",
        "priority": 64,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Talk - Please Talk To Me",
        "category": "Trying to Talk",
        "subcategory": "Please talk to me / listen to me",
        "student_query": "please talk to me",
        "alternate_queries": "mujhe baat karni hai",
        "response": "I hear you! 😊 I'm always here for your learning journey. Want to watch today's video? It's actually really interesting!",
        "match_type": "Fuzzy",
        "priority": 63,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Talk - Listen To Me",
        "category": "Trying to Talk",
        "subcategory": "Please talk to me / listen to me",
        "student_query": "listen to me",
        "alternate_queries": "I'm bored\nbore ho raha hun\nbore ho rahi hun",
        "response": "I'm listening! 🤗 More importantly, I care about your learning. The best way I can help is by guiding you through today's activity — let's do it together!",
        "match_type": "Fuzzy",
        "priority": 62,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Warm",
    },
    {
        "title": "Help - Problem Hai",
        "category": "Trying to Talk",
        "subcategory": "I have a problem / I need help",
        "student_query": "problem hai",
        "alternate_queries": "mujhe madad chahiye",
        "response": "Oh no, I hope you're okay! 🤗 I'm here to help with your learning activities. If it's a problem with the video or quiz, just tell me what's happening — I'll try my best. If it's something else, please speak to your teacher or a trusted adult at home. 💙",
        "match_type": "Fuzzy",
        "priority": 61,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Supportive",
    },
    {
        "title": "Help - General Issue",
        "category": "Trying to Talk",
        "subcategory": "I have a problem / I need help",
        "student_query": "I have a problem",
        "alternate_queries": "help me\nissue",
        "response": "I'm here! 😊 Tell me what's going on — is it with the video, the quiz, or the submission? I'll do my best to help you sort it out!",
        "match_type": "Fuzzy",
        "priority": 60,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Supportive",
    },
    {
        "title": "Submission - Done",
        "category": "Trying to Talk",
        "subcategory": "Submission done / I already did it",
        "student_query": "Done",
        "alternate_queries": "I have done\nho gaya",
        "response": "That's amazing! 🎉 You're a star for completing your submission! Your teacher will be so proud. Keep up the great work — you're on your way to being a future leader! 🌟",
        "match_type": "Fuzzy",
        "priority": 59,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Celebratory",
    },
    {
        "title": "Submission - Kar Diya",
        "category": "Trying to Talk",
        "subcategory": "Submission done / I already did it",
        "student_query": "kar diya",
        "alternate_queries": "submit kar diya",
        "response": "Wonderful! ✅ Great job finishing your activity! Every submission you complete is a step forward. See you next week for more! 💪",
        "match_type": "Fuzzy",
        "priority": 58,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Celebratory",
    },
    {
        "title": "Submission - Points Earned",
        "category": "Trying to Talk",
        "subcategory": "Submission done / I already did it",
        "student_query": "How many points do I earn from activity submission?",
        "alternate_queries": "submission points",
        "response": "For every activity you complete, you get:\nWatching the video: 10 Points 📺\nDoing the submission: 25 Points 📝",
        "match_type": "Fuzzy",
        "priority": 57,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Submission - Streak",
        "category": "Trying to Talk",
        "subcategory": "Submission done / I already did it",
        "student_query": "What is a submission streak",
        "alternate_queries": "submission streak",
        "response": "If you send in your activities every single week without missing one, you get a \"submission streak\"! 🏃💨",
        "match_type": "Fuzzy",
        "priority": 56,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Informative",
    },
    {
        "title": "Refuse - No I Wont",
        "category": "Trying to Talk",
        "subcategory": "Refusing to submit / not willing",
        "student_query": "no I won't",
        "alternate_queries": "I will not submit\nnot doing it",
        "response": "No pressure at all! 😊 But I believe you're capable of amazing things. Even a small submission — just sharing one idea — counts! What do you think? Give it a try?",
        "match_type": "Fuzzy",
        "priority": 55,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Encouraging",
    },
    {
        "title": "Refuse - Nahi Karunga",
        "category": "Trying to Talk",
        "subcategory": "Refusing to submit / not willing",
        "student_query": "nahi karunga",
        "alternate_queries": "boring",
        "response": "That's okay! 🤗 Sometimes we don't feel like it — and that's totally normal. But you've made it this far! There's no right or wrong submission — just share what YOU think. I'd love to see your ideas. 💙",
        "match_type": "Fuzzy",
        "priority": 54,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Encouraging",
    },
    {
        "title": "Admin - School Questions",
        "category": "Trying to Talk",
        "subcategory": "School open/closed or admin questions",
        "student_query": "school open hai",
        "alternate_queries": "registration number\nmy class\nwhich teacher\nschool closed",
        "response": "That's a great question, but I'm only able to help with your TAP learning activities! 😊 For school information please check with your teacher or school.",
        "match_type": "Fuzzy",
        "priority": 53,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Polite",
    },
    {
        "title": "Stuck - No Ideas",
        "category": "Trying to Talk",
        "subcategory": "No ideas for submission / stuck",
        "student_query": "no ideas",
        "alternate_queries": "kya likhun\nwhat to do\nkuch samajh nahi\nI don't know what to submit",
        "response": "Don't worry — everyone gets stuck sometimes! 😊 Here's a tip: {Curriculum definition}. There's no wrong answer.",
        "match_type": "Fuzzy",
        "priority": 52,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Encouraging",
    },
    {
        "title": "Excitement - Positive Emotion",
        "category": "Trying to Talk",
        "subcategory": "Expressing excitement / positive emotion",
        "student_query": "I'm impressed",
        "alternate_queries": "this is fun\nmaza aa gaya\nI love TAP buddy\nawesome",
        "response": "That makes me SO happy to hear! 🎉 You make this worth it! Keep that energy — curious, excited learners like you are going to do great things.",
        "match_type": "Fuzzy",
        "priority": 51,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Encouraging",
    },
    {
        "title": "Promotion - New Class",
        "category": "Trying to Talk",
        "subcategory": "Class change / promotion pride",
        "student_query": "4th class se 5th",
        "alternate_queries": "pass ho gaya\nPromoted\nnaya class\nbadhai do",
        "response": "Congratulations! 🎊🎉 You should be so proud of yourself! Keep it up, rockstar! 🌟",
        "match_type": "Fuzzy",
        "priority": 50,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Celebratory",
    },
    {
        "title": "Request - Hindi Video",
        "category": "Requests",
        "subcategory": "Please send video in a different language",
        "student_query": "hindi mein video chahiye",
        "alternate_queries": "",
        "response": "I totally understand! 😊 Right now, videos are only available in the language set for your course.",
        "match_type": "Fuzzy",
        "priority": 49,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Polite",
    },
    {
        "title": "Request - Different Language",
        "category": "Requests",
        "subcategory": "Please send video in a different language",
        "student_query": "different language",
        "alternate_queries": "English mein chahiye",
        "response": "I totally understand! 😊 But right now, I cant change the language.",
        "match_type": "Fuzzy",
        "priority": 48,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Polite",
    },
    {
        "title": "Request - Wrong Name",
        "category": "Requests",
        "subcategory": "Wrong name / I am X not Y",
        "student_query": "I am not [name]",
        "alternate_queries": "mera naam [X] hai\nwrong name",
        "response": "Oh, my apologies for that!😢 Names are important and I want to get yours right. For a name correction, please ask your teacher to contact the TAP team. In the meantime, I'm still here to help you learn. 💙",
        "match_type": "Fuzzy",
        "priority": 47,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Apologetic",
    },
    {
        "title": "Request - Submission Explain",
        "category": "Requests",
        "subcategory": "Can you explain the submission / what do I do?",
        "student_query": "submission kya hai",
        "alternate_queries": "explain submission\nwhat to submit\nsubmission kaise karu\nI don't understand submission",
        "response": "Great question! 🤗 The submission is {Curriculum definition}",
        "match_type": "Fuzzy",
        "priority": 46,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Helpful",
    },
    {
        "title": "Request - How To Submit",
        "category": "Requests",
        "subcategory": "Can you explain the submission / what do I do?",
        "student_query": "How to submit?",
        "alternate_queries": "how to submit",
        "response": "It only takes 3 easy steps to send in your work:\nWatch the video and follow the instructions. 🎥\nCreated your submission activity. ✍️\nTake a photo or share your video on TAP Buddy. 📸✨",
        "match_type": "Fuzzy",
        "priority": 45,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Helpful",
    },
    {
        "title": "Request - Special Gem",
        "category": "Requests",
        "subcategory": "Can you explain the submission / what do I do?",
        "student_query": "how to get special gem?",
        "alternate_queries": "",
        "response": "Just stay active and make sure you send in your activity every week! 🗓️⭐",
        "match_type": "Fuzzy",
        "priority": 44,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Helpful",
    },
    {
        "title": "Request - Need Time",
        "category": "Requests",
        "subcategory": "I need more time / can't do it now",
        "student_query": "time chahiye",
        "alternate_queries": "I will need time\nbusy hoon\nnot now",
        "response": "No problem at all! 😊 Take your time — learning happens at your pace. When you're ready, just come back here and we'll pick up from where you left off! I'll be right here. ⏳",
        "match_type": "Fuzzy",
        "priority": 43,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Supportive",
    },
    {
        "title": "Request - Later",
        "category": "Requests",
        "subcategory": "I need more time / can't do it now",
        "student_query": "baad mein karunga",
        "alternate_queries": "",
        "response": "Of course! 🤗 Life gets busy sometimes. Just try to complete it before the week is up so you don't miss out! I'll be waiting for you. 💙",
        "match_type": "Fuzzy",
        "priority": 42,
        "language": "Hindi",
        "user_type": "Student",
        "response_tone": "Supportive",
    },
    {
        "title": "Request - Continue",
        "category": "Requests",
        "subcategory": "Yes, I want to / Continue / Ready",
        "student_query": "Continue",
        "alternate_queries": "Yes\nHaan\nchalo",
        "response": "Let's go! 🚀",
        "match_type": "Fuzzy",
        "priority": 41,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Motivating",
    },
    {
        "title": "Request - Ready",
        "category": "Requests",
        "subcategory": "Yes, I want to / Continue / Ready",
        "student_query": "Ready",
        "alternate_queries": "I want to",
        "response": "Love the attitude! 💪",
        "match_type": "Fuzzy",
        "priority": 40,
        "language": "English",
        "user_type": "Student",
        "response_tone": "Motivating",
    },
]


def _upsert_entry(entry: Dict[str, Any]) -> None:
    filters = {"title": entry["title"]}
    meta_fields = {
        field.fieldname
        for field in frappe.get_meta(DOCTYPE).fields
        if getattr(field, "fieldname", None)
    }
    if frappe.db.exists(DOCTYPE, filters):
        doc = frappe.get_doc(DOCTYPE, filters)
    else:
        doc = frappe.new_doc(DOCTYPE)

    for field, value in entry.items():
        if field not in meta_fields:
            continue
        setattr(doc, field, value)

    if doc.is_new():
        doc.insert(ignore_permissions=True)
    else:
        doc.save(ignore_permissions=True)


def execute() -> None:
    _ensure_doctype_loaded()

    for entry in SEED_DATA:
        _upsert_entry(entry)

    try:
        frappe.cache().delete(CACHE_KEY)
    except Exception:
        pass

    frappe.db.commit()
